import type {
  Assessment, Candidate, CanonicalDuplicateCandidate, CanonicalMergePreview, CanonicalEntity, PostMergeReconciliation, DocItem, OpenAlephReviewStatus, EnrichmentCluster, EnrichmentSession,
  EntityDossier, ExternalRelCandidates, ExternalRelationshipReview, ExtractionCandidate, ExtractionLineage, ExtractionLineageEnvelope,
  Claim, ClaimEvidenceRow, EvidencePoolRow, EvidenceRecord, SourceRecord, Finding, HistoryRow, IdResponse, Investigation, LeadItem, Relationship, GraphResponse, SearchResult, TimelineEvent, BackupPreview, BackupRestoreResult, SettingsStatus, ConnectorCredentialMutation, InvestigationDeletionPreview, InvestigationDeletionResult, OrphanStoragePreview, SecurityAuditView, SecurityAuditSummary, SecurityAuditRetentionPreview, SecurityAuditRetentionResult, ProvenanceTrace,
} from './api-types';

type Obj=Record<string,unknown>;
export class ApiPayloadError extends Error {
  constructor(public endpoint:string, public issue:string){super(`Invalid API payload from ${endpoint}: ${issue}`);this.name='ApiPayloadError';}
}
const isObj=(v:unknown):v is Obj=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const str=(o:Obj,k:string)=>typeof o[k]==='string';
const num=(o:Obj,k:string)=>typeof o[k]==='number'&&Number.isFinite(o[k] as number);
const arr=(o:Obj,k:string)=>Array.isArray(o[k]);
const optStr=(o:Obj,k:string)=>o[k]===undefined||o[k]===null||typeof o[k]==='string';
const record=(o:Obj,k:string)=>isObj(o[k]);
const fail=(endpoint:string,issue:string):never=>{throw new ApiPayloadError(endpoint,issue)};
const arrayOf=<T>(value:unknown,endpoint:string,name:string,guard:(v:unknown)=>v is T):T[]=>{
  if(!Array.isArray(value))return fail(endpoint,`${name} must be an array`);
  const rows:unknown[]=value;
  rows.forEach((item:unknown,i:number)=>{if(!guard(item))fail(endpoint,`${name}[${i}] has an unexpected shape`)});
  return rows as T[];
};

export const isSourceRecord=(v:unknown):v is SourceRecord=>isObj(v)&&str(v,'id')&&str(v,'investigation_id')&&str(v,'title')&&str(v,'source_type')&&optStr(v,'url');
export const isEvidenceRecord=(v:unknown):v is EvidenceRecord=>isObj(v)&&str(v,'id')&&str(v,'source_id')&&optStr(v,'quote')&&optStr(v,'locator')&&optStr(v,'notes');
export const isClaim=(v:unknown):v is Claim=>isObj(v)&&str(v,'id')&&str(v,'investigation_id')&&str(v,'text')&&str(v,'status')&&num(v,'confidence');
export const isClaimEvidenceRow=(v:unknown):v is ClaimEvidenceRow=>isObj(v)&&str(v,'id')&&str(v,'stance')&&isObj(v.evidence)&&str(v.evidence,'id')&&str(v.evidence,'source_id')&&(v.source===null||v.source===undefined||(isObj(v.source)&&str(v.source,'id')&&str(v.source,'title')));
export const isEvidencePoolRow=(v:unknown):v is EvidencePoolRow=>isObj(v)&&isObj(v.evidence)&&str(v.evidence,'id')&&str(v.evidence,'source_id')&&isObj(v.source)&&str(v.source,'id')&&str(v.source,'title');
export const isIdResponse=(v:unknown):v is IdResponse=>isObj(v)&&str(v,'id');

export const isBackupPreview=(v:unknown):v is BackupPreview=>isObj(v)&&str(v,'format')&&num(v,'version')&&isObj(v.investigation)&&str(v.investigation,'id')&&str(v.investigation,'name')&&record(v,'record_counts')&&num(v,'document_file_count')&&num(v,'missing_document_count')&&arr(v,'warnings')&&arr(v,'conflicts')&&typeof v.can_restore==='boolean'&&typeof v.restore_api_enabled==='boolean'&&(v.conflicts as unknown[]).every(x=>isObj(x)&&str(x,'kind')&&str(x,'table')&&str(x,'id')&&str(x,'message'));
export const isBackupRestoreResult=(v:unknown):v is BackupRestoreResult=>isObj(v)&&str(v,'investigation_id')&&record(v,'restored_counts')&&record(v,'manifest');
const isConnectorStatus=(v:unknown)=>isObj(v)&&typeof v.configured==='boolean'&&(v.source===undefined||['local_store','environment','none'].includes(String(v.source)))&&(v.local_store_present===undefined||typeof v.local_store_present==='boolean')&&(v.permissions_restricted===undefined||typeof v.permissions_restricted==='boolean');
export const isSettingsStatus=(v:unknown):v is SettingsStatus=>isObj(v)&&str(v,'environment')&&str(v,'database')&&str(v,'document_storage_dir')&&record(v,'limits')&&typeof v.restore_api_enabled==='boolean'&&isObj(v.document_extraction)&&typeof v.document_extraction.pdf_ocr_enabled==='boolean'&&str(v.document_extraction,'pdf_ocr_language')&&num(v.document_extraction,'pdf_ocr_dpi')&&num(v.document_extraction,'pdf_ocr_min_native_chars')&&typeof v.document_extraction.local_entity_suggestions_enabled==='boolean'&&['workbench_local','openaleph_ftm_analyze'].includes(String(v.document_extraction.entity_extraction_owner))&&isObj(v.document_extraction.ocr_runtime)&&typeof v.document_extraction.ocr_runtime.available==='boolean'&&arr(v.document_extraction.ocr_runtime,'requested_languages')&&arr(v.document_extraction.ocr_runtime,'missing_languages')&&str(v.document_extraction.ocr_runtime,'detail')&&isObj(v.access)&&typeof v.access.remote_api_enabled==='boolean'&&['local_only','shared_bearer','persisted_users'].includes(String(v.access.mode))&&typeof v.access.token_configured==='boolean'&&arr(v,'cors_allowed_origins')&&isObj(v.connectors)&&isConnectorStatus(v.connectors.aleph)&&isConnectorStatus(v.connectors.opensanctions);
export const isConnectorCredentialMutation=(v:unknown):v is ConnectorCredentialMutation=>isObj(v)&&['aleph','opensanctions'].includes(String(v.provider))&&isConnectorStatus(v);
export const isInvestigationDeletionPreview=(v:unknown):v is InvestigationDeletionPreview=>isObj(v)&&str(v,'investigation_id')&&str(v,'investigation_name')&&record(v,'record_counts')&&num(v,'record_total')&&arr(v,'document_files')&&record(v,'document_file_summary')&&arr(v,'unsafe_paths')&&typeof v.can_delete==='boolean'&&str(v,'requires_confirmation');
export const isInvestigationDeletionResult=(v:unknown):v is InvestigationDeletionResult=>isObj(v)&&str(v,'investigation_id')&&typeof v.deleted==='boolean'&&record(v,'deleted_record_counts')&&num(v,'deleted_record_total')&&num(v,'document_files_deleted')&&num(v,'shared_document_files_preserved')&&num(v,'missing_document_files');
export const isOrphanStoragePreview=(v:unknown):v is OrphanStoragePreview=>isObj(v)&&str(v,'storage_root')&&arr(v,'orphan_files')&&num(v,'orphan_file_count')&&num(v,'orphan_bytes')&&arr(v,'unsafe_document_references')&&typeof v.cleanup_available==='boolean'&&v.policy==='preview_only_retain_by_default'&&(v.orphan_files as unknown[]).every(x=>isObj(x)&&str(x,'relative_path')&&num(x,'size_bytes')&&num(x,'modified_at')&&x.action==='retain_until_explicit_cleanup');
export const isInvestigation=(v:unknown):v is Investigation=>isObj(v)&&str(v,'id')&&str(v,'name');
export const isCanonicalEntity=(v:unknown):v is CanonicalEntity=>isObj(v)&&str(v,'id')&&str(v,'caption')&&str(v,'schema')&&record(v,'properties');
export const isFinding=(v:unknown):v is Finding=>isObj(v)&&str(v,'id')&&str(v,'provider')&&str(v,'caption')&&record(v,'properties')&&str(v,'review_status')&&optStr(v,'schema')&&optStr(v,'source_url');
export const isCandidate=(v:unknown):v is Candidate=>isObj(v)&&str(v,'entity_id')&&str(v,'caption')&&str(v,'schema')&&num(v,'score');
export const isCanonicalDuplicateCandidate=(v:unknown):v is CanonicalDuplicateCandidate=>isObj(v)&&str(v,'entity_id')&&str(v,'caption')&&str(v,'schema')&&num(v,'score')&&(v.latest_decision===undefined||v.latest_decision===null||(isObj(v.latest_decision)&&str(v.latest_decision,'id')&&['same','different','unsure'].includes(String(v.latest_decision.decision))&&num(v.latest_decision,'confidence')));
export const isCanonicalMergePreview=(v:unknown):v is CanonicalMergePreview=>isObj(v)&&isObj(v.source)&&str(v.source,'id')&&str(v.source,'caption')&&str(v.source,'schema')&&isObj(v.target)&&str(v.target,'id')&&str(v.target,'caption')&&str(v.target,'schema')&&record(v,'references')&&num(v,'total_references')&&arr(v,'blockers')&&typeof v.can_execute==='boolean'&&str(v,'preview_digest');
const isReconciliationDecision=(v:unknown)=>isObj(v)&&str(v,'id')&&['statement','relationship'].includes(String(v.record_type))&&str(v,'record_a_id')&&str(v,'record_b_id')&&['duplicate','keep_separate','unsure'].includes(String(v.decision));
const isReconciliationStatement=(v:unknown)=>isObj(v)&&str(v,'id')&&str(v,'prop')&&str(v,'value')&&str(v,'dataset')&&optStr(v,'origin')&&optStr(v,'original_value');
const isReconciliationPair=(v:unknown,kind:'statement'|'relationship')=>isObj(v)&&v.record_type===kind&&typeof v.same_assertion==='boolean'&&typeof v.provenance_differs==='boolean'&&(v.latest_decision===undefined||v.latest_decision===null||isReconciliationDecision(v.latest_decision))&&((kind==='statement'&&isReconciliationStatement(v.record_a)&&isReconciliationStatement(v.record_b))||(kind==='relationship'&&isRelationship(v.record_a)&&isRelationship(v.record_b)));
export const isPostMergeReconciliation=(v:unknown):v is PostMergeReconciliation=>isObj(v)&&str(v,'entity_id')&&arr(v,'statement_duplicates')&&arr(v,'relationship_duplicates')&&isObj(v.summary)&&num(v.summary,'statement_pairs')&&num(v.summary,'relationship_pairs')&&num(v.summary,'unresolved_pairs')&&(v.statement_duplicates as unknown[]).every(x=>isReconciliationPair(x,'statement'))&&(v.relationship_duplicates as unknown[]).every(x=>isReconciliationPair(x,'relationship'));
export const isAssessment=(v:unknown):v is Assessment=>isObj(v)&&str(v,'id')&&str(v,'prop')&&str(v,'value')&&str(v,'status')&&optStr(v,'entity_id');
const isEndpoint=(v:unknown)=>isObj(v)&&str(v,'id')&&str(v,'caption')&&str(v,'schema');
const isRelationshipReconciliation=(v:unknown)=>isObj(v)&&str(v,'decision_id')&&v.decision==='duplicate'&&str(v,'preferred_record_id')&&str(v,'secondary_record_id')&&typeof v.is_preferred==='boolean'&&typeof v.suppressed_duplicate==='boolean'&&(v.suppressed_duplicate_ids===undefined||Array.isArray(v.suppressed_duplicate_ids))&&(v.suppressed_duplicate_count===undefined||typeof v.suppressed_duplicate_count==='number');
export const isRelationship=(v:unknown):v is Relationship=>isObj(v)&&str(v,'id')&&str(v,'relationship_entity_id')&&str(v,'schema')&&str(v,'caption')&&record(v,'properties')&&isEndpoint(v.source)&&isEndpoint(v.target)&&(v.reconciliation===undefined||isRelationshipReconciliation(v.reconciliation));
export const isTimelineEvent=(v:unknown):v is TimelineEvent=>isObj(v)&&str(v,'id')&&str(v,'kind')&&str(v,'title')&&str(v,'date_start')&&str(v,'precision')&&str(v,'verification_status')&&record(v,'provenance')&&record(v,'refs');
export const isSearchResult=(v:unknown):v is SearchResult=>isObj(v)&&str(v,'type')&&['canonical','evidence','reporting','workflow','review','external_lead','other'].includes(String(v.group))&&str(v,'id')&&str(v,'investigation_id')&&str(v,'title')&&str(v,'snippet')&&num(v,'score')&&record(v,'provenance')&&record(v,'metadata');
export const isDocItem=(v:unknown):v is DocItem=>isObj(v)&&str(v,'id')&&str(v,'filename')&&str(v,'source_id')&&str(v,'extraction_status')&&num(v,'chunk_count')&&record(v,'candidate_counts');
const isCorpusBinding=(v:unknown)=>isObj(v)&&str(v,'id')&&str(v,'investigation_id')&&str(v,'provider')&&str(v,'collection_id')&&str(v,'status')&&optStr(v,'foreign_id')&&optStr(v,'collection_label');
const isDocumentCorpusSync=(v:unknown)=>isObj(v)&&str(v,'id')&&str(v,'document_id')&&str(v,'investigation_id')&&str(v,'provider')&&str(v,'collection_id')&&str(v,'status')&&optStr(v,'provider_record_id')&&optStr(v,'error');
const isNestedCountRecord=(v:unknown)=>isObj(v)&&Object.values(v).every(item=>isObj(item)&&Object.values(item).every(value=>typeof value==='number'&&Number.isFinite(value)));
export const isOpenAlephReviewStatus=(v:unknown):v is OpenAlephReviewStatus=>isObj(v)&&str(v,'document_id')&&str(v,'investigation_id')&&v.provider==='openaleph'&&str(v,'document_extraction_status')&&(v.binding===null||isCorpusBinding(v.binding))&&(v.sync===null||isDocumentCorpusSync(v.sync))&&typeof v.ready_for_import==='boolean'&&isNestedCountRecord(v.candidate_counts)&&num(v,'provider_candidate_total')&&num(v,'provider_candidate_pending_review')&&num(v,'provider_candidate_accepted')&&num(v,'provider_candidate_rejected');
export const isExtractionCandidate=(v:unknown):v is ExtractionCandidate=>isObj(v)&&str(v,'id')&&str(v,'candidate_type')&&record(v,'payload')&&str(v,'review_status');
const isTraceCandidate=(v:unknown)=>isObj(v)&&str(v,'id')&&str(v,'investigation_id')&&str(v,'document_id')&&str(v,'candidate_type')&&record(v,'payload')&&num(v,'confidence')&&str(v,'review_status')&&optStr(v,'chunk_id')&&optStr(v,'accepted_record_type')&&optStr(v,'accepted_record_id')&&optStr(v,'reviewer_note');
const isTraceDocument=(v:unknown)=>isObj(v)&&str(v,'id')&&str(v,'investigation_id')&&str(v,'source_id')&&str(v,'filename')&&str(v,'sha256')&&str(v,'extraction_status')&&optStr(v,'mime_type');
const isTraceSource=(v:unknown)=>isObj(v)&&str(v,'id')&&str(v,'investigation_id')&&str(v,'title')&&str(v,'source_type')&&optStr(v,'url');
const isTraceChunk=(v:unknown)=>isObj(v)&&str(v,'id')&&str(v,'document_id')&&num(v,'ordinal')&&str(v,'locator')&&str(v,'text')&&str(v,'extraction_method')&&['ocr','native_pdf','native_text'].includes(v.extraction_method as string)&&(v.page_number===undefined||v.page_number===null||typeof v.page_number==='number');
export const isExtractionLineage=(v:unknown):v is ExtractionLineage=>isObj(v)&&isTraceCandidate(v.candidate)&&(v.document===null||isTraceDocument(v.document))&&(v.source===null||isTraceSource(v.source))&&(v.chunk===null||isTraceChunk(v.chunk));
export const isExtractionLineageEnvelope=(v:unknown):v is ExtractionLineageEnvelope=>isObj(v)&&typeof v.found==='boolean'&&(v.lineage===null||isExtractionLineage(v.lineage));
export const isLeadItem=(v:unknown):v is LeadItem=>isObj(v)&&str(v,'id')&&str(v,'title')&&str(v,'status')&&str(v,'priority')&&arr(v,'links')&&arr(v,'tasks')&&isObj(v.triage)&&typeof v.triage.needs_attention==='boolean'&&num(v.triage,'attention_score')&&isObj(v.triage.stance_counts)&&num(v.triage.stance_counts,'supports')&&num(v.triage.stance_counts,'contradicts')&&num(v.triage.stance_counts,'context')&&num(v.triage,'linked_claim_count')&&num(v.triage,'disputed_claim_count')&&arr(v.triage,'reasons');
export const isHistoryRow=(v:unknown):v is HistoryRow=>isObj(v)&&str(v,'prop')&&str(v,'value')&&typeof v.canonical==='boolean'&&num(v,'support_count')&&num(v,'conflict_count')&&arr(v,'canonical_statements')&&arr(v,'external_assessments');
export const isExternalRelCandidates=(v:unknown):v is ExternalRelCandidates=>isObj(v)&&str(v,'schema')&&str(v,'source_prop')&&str(v,'target_prop')&&str(v,'source_external_id')&&str(v,'target_external_id')&&arr(v,'source_candidates')&&arr(v,'target_candidates')&&(v.source_candidates as unknown[]).every(isCandidate)&&(v.target_candidates as unknown[]).every(isCandidate);
export const isExternalRelationshipReview=(v:unknown):v is ExternalRelationshipReview=>isObj(v)&&str(v,'id')&&str(v,'decision');
export const isEnrichmentSession=(v:unknown):v is EnrichmentSession=>isObj(v)&&str(v,'id')&&str(v,'status')&&arr(v,'runs')&&(v.runs as unknown[]).every(x=>isObj(x)&&str(x,'provider')&&str(x,'status'));
export const isEnrichmentCluster=(v:unknown):v is EnrichmentCluster=>isObj(v)&&str(v,'cluster_key')&&num(v,'score')&&arr(v,'finding_ids')&&arr(v,'findings');
export const isEntityDossier=(v:unknown):v is EntityDossier=>isObj(v)&&isCanonicalEntity(v.entity)&&isObj(v.summary)&&arr(v,'relationships')&&arr(v,'claims')&&arr(v,'evidence')&&(v.relationships as unknown[]).every(isRelationship);

export async function jsonUnknown(response:Response,endpoint:string):Promise<unknown>{
  try{return await response.json()}catch{fail(endpoint,'response was not valid JSON')}
}
export async function jsonArray<T>(response:Response,endpoint:string,name:string,guard:(v:unknown)=>v is T):Promise<T[]>{
  return arrayOf(await jsonUnknown(response,endpoint),endpoint,name,guard);
}
export async function jsonObject<T>(response:Response,endpoint:string,name:string,guard:(v:unknown)=>v is T):Promise<T>{
  const value=await jsonUnknown(response,endpoint);if(!guard(value))return fail(endpoint,`${name} has an unexpected shape`);return value;
}
export function parseInvestigationList(v:unknown,e:string){return arrayOf(v,e,'investigations',isInvestigation)}
export function parseFindingList(v:unknown,e:string){return arrayOf(v,e,'findings',isFinding)}
export function parseEntityList(v:unknown,e:string){return arrayOf(v,e,'entities',isCanonicalEntity)}
export function parseRelationshipList(v:unknown,e:string){return arrayOf(v,e,'relationships',isRelationship)}
export function parseTimelineBody(v:unknown,e:string):{events:TimelineEvent[],verification_counts:Record<string,number>}{if(!isObj(v))return fail(e,'timeline body has an unexpected shape');const events=v.events,counts=v.verification_counts;if(!Array.isArray(events)||!isObj(counts))return fail(e,'timeline body has an unexpected shape');return {events:arrayOf(events,e,'events',isTimelineEvent),verification_counts:counts as Record<string,number>}}
export function parseSearchBody(v:unknown,e:string):{results:SearchResult[],counts:Record<string,number>,group_counts:Record<string,number>}{if(!isObj(v))return fail(e,'search body has an unexpected shape');const results=v.results,counts=v.counts,groupCounts=v.group_counts;if(!Array.isArray(results)||!isObj(counts)||!isObj(groupCounts))return fail(e,'search body has an unexpected shape');return {results:arrayOf(results,e,'results',isSearchResult),counts:counts as Record<string,number>,group_counts:groupCounts as Record<string,number>}}
export function parseLeadQueue(v:unknown,e:string):LeadItem[]{if(!isObj(v))return fail(e,'lead queue has an unexpected shape');const items=v.items;if(!Array.isArray(items))return fail(e,'lead queue has an unexpected shape');return arrayOf(items,e,'items',isLeadItem)}
export function parseGraph(v:unknown,e:string):GraphResponse{if(!isObj(v)||!Array.isArray(v.nodes)||!Array.isArray(v.edges)||!Array.isArray(v.schemas)||!isObj(v.reconciliation))return fail(e,'graph has an unexpected shape');const rec=v.reconciliation;if(typeof rec.collapsed_by_default!=='boolean'||!num(rec,'suppressed_duplicate_count')||!num(rec,'underlying_edge_count')||!num(rec,'visible_edge_count'))return fail(e,'graph reconciliation summary has an unexpected shape');return {nodes:arrayOf(v.nodes,e,'nodes',isCanonicalEntity),edges:arrayOf(v.edges,e,'edges',isRelationship),schemas:(v.schemas as unknown[]).map((x,i)=>{if(typeof x!=='string')return fail(e,`schemas[${i}] must be a string`);return x}),reconciliation:rec as GraphResponse['reconciliation']}}
export function parseProviders(v:unknown,e:string):string[]{if(!isObj(v))return fail(e,'providers has an unexpected shape');const providers=v.providers;if(!Array.isArray(providers)||!providers.every((x:unknown)=>typeof x==='string'))return fail(e,'providers has an unexpected shape');return providers as string[]}

export const isSecurityAuditRecord=(v:unknown)=>isObj(v)&&str(v,'timestamp')&&str(v,'event')&&str(v,'request_id')&&str(v,'method')&&str(v,'path')&&num(v,'status_code')&&typeof v.local_request==='boolean'&&optStr(v,'client_host');
export const isSecurityAuditView=(v:unknown):v is SecurityAuditView=>isObj(v)&&arr(v,'records')&&num(v,'returned')&&num(v,'total_matched')&&num(v,'offset')&&typeof v.has_more==='boolean'&&(v.next_offset===null||typeof v.next_offset==='number')&&num(v,'malformed_lines')&&num(v,'file_bytes')&&(v.records as unknown[]).every(isSecurityAuditRecord);
export const isSecurityAuditSummary=(v:unknown):v is SecurityAuditSummary=>isObj(v)&&num(v,'total_records')&&num(v,'malformed_lines')&&num(v,'local_records')&&num(v,'remote_records')&&record(v,'by_event')&&record(v,'by_method')&&record(v,'by_status')&&num(v,'file_bytes');
export const isSecurityAuditRetentionPreview=(v:unknown):v is SecurityAuditRetentionPreview=>isObj(v)&&num(v,'keep_days')&&num(v,'max_records')&&num(v,'total_lines')&&num(v,'valid_records')&&num(v,'malformed_lines')&&num(v,'would_keep')&&num(v,'would_remove')&&num(v,'file_bytes');
export const isSecurityAuditRetentionResult=(v:unknown):v is SecurityAuditRetentionResult=>isObj(v)&&isSecurityAuditRetentionPreview(v)&&num(v,'removed')&&typeof (v as Obj).applied==='boolean';

export const isProvenanceTrace=(v:unknown):v is ProvenanceTrace=>isObj(v)&&['entity','claim','evidence','relationship','source','document','lead','task'].includes(String(v.record_type))&&str(v,'record_id')&&str(v,'investigation_id')&&record(v,'root')&&(v.extraction_lineage===null||isExtractionLineage(v.extraction_lineage))&&arr(v,'evidence_links')&&arr(v,'claim_links')&&arr(v,'relationships')&&arr(v,'lead_links')&&(v.relationships as unknown[]).every(isRelationship);
